name: Custom Rom Builder Samsung Galaxy A01/M01

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      GSI:
        description: 'Direct link for GSI image'
        required: true
        default: 'https://sourceforge.net/projects/andyyan-gsi/files/lineage-19.x/lineage-19.1-20230715-UNOFFICIAL-a64_bgN.img.xz'
      ARCH:
        description: 'Arm32 or Arm64 (32 or 64)'
        required: true
        default: '32'
      NAME:
        description: 'Rom Name'
        required: true
        default: 'LineageOS_19.1_SDM439_ARM32_Gapps'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip xz-utils unzip p7zip-full wget

      - name: Preparing Files
        run: |
          wget https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/custom_rom_builder_439.zip
          unzip custom_rom_builder_439.zip
          rm custom_rom_builder_439.zip
          git clone https://github.com/omar-ly/Custom-Rom-Builder-For-Samsung-Galaxy-A01-M01

      - name: Downloading your GSI
        run: |
          mkdir -p temp  # Create the directory if it doesn't exist
          wget -P "./temp" "${{ github.event.inputs.GSI }}"
          chmod +x *
          chmod +x ./bin/*

      - name: Building
        run: |
          ./arm${{ github.event.inputs.ARCH }}_git

      - name: Uploading The Zip
        uses: actions/upload-artifact@v4 # Use v4 or later
        with:
          name: ${{ github.event.inputs.NAME }}
          path: ./zip/Custom_Rom_SDM439.zip
